/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import java.awt.Color;

/**
 *
 * @author macbookpro
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    Color DefaultColor, ClickedColor;
    public Dashboard() {
        initComponents();
        DefaultColor = new Color(251,247,244);
        ClickedColor = new Color(238,230,226);
        
        TrangChu.setBackground(ClickedColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TaiKhoan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DatTiec = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TrangChu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DanhMuc = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TraCuu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ThongKe = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        NhanVien = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 850));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(251, 247, 244));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TaiKhoan.setBackground(new java.awt.Color(251, 247, 244));
        TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TaiKhoanMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vector.png"))); // NOI18N
        jLabel7.setText("Tài khoản");

        javax.swing.GroupLayout TaiKhoanLayout = new javax.swing.GroupLayout(TaiKhoan);
        TaiKhoan.setLayout(TaiKhoanLayout);
        TaiKhoanLayout.setHorizontalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        TaiKhoanLayout.setVerticalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 270, 56));

        DatTiec.setBackground(new java.awt.Color(251, 247, 244));
        DatTiec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatTiecMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DatTiecMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jLabel2.setText("Đặt tiệc cưới");

        javax.swing.GroupLayout DatTiecLayout = new javax.swing.GroupLayout(DatTiec);
        DatTiec.setLayout(DatTiecLayout);
        DatTiecLayout.setHorizontalGroup(
            DatTiecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatTiecLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        DatTiecLayout.setVerticalGroup(
            DatTiecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatTiecLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.add(DatTiec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 56));

        TrangChu.setBackground(new java.awt.Color(251, 247, 244));
        TrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TrangChuMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TrangChu.png"))); // NOI18N
        jLabel1.setText("Trang chủ");

        javax.swing.GroupLayout TrangChuLayout = new javax.swing.GroupLayout(TrangChu);
        TrangChu.setLayout(TrangChuLayout);
        TrangChuLayout.setHorizontalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        TrangChuLayout.setVerticalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.add(TrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 270, 56));

        DanhMuc.setBackground(new java.awt.Color(251, 247, 244));
        DanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DanhMucMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DanhMuc.png"))); // NOI18N
        jLabel4.setText("Danh mục");

        javax.swing.GroupLayout DanhMucLayout = new javax.swing.GroupLayout(DanhMuc);
        DanhMuc.setLayout(DanhMucLayout);
        DanhMucLayout.setHorizontalGroup(
            DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhMucLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        DanhMucLayout.setVerticalGroup(
            DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhMucLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.add(DanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 270, 56));

        TraCuu.setBackground(new java.awt.Color(251, 247, 244));
        TraCuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TraCuuMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jLabel3.setText("Tra cứu tiệc");

        javax.swing.GroupLayout TraCuuLayout = new javax.swing.GroupLayout(TraCuu);
        TraCuu.setLayout(TraCuuLayout);
        TraCuuLayout.setHorizontalGroup(
            TraCuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TraCuuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        TraCuuLayout.setVerticalGroup(
            TraCuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TraCuuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(TraCuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 56));

        ThongKe.setBackground(new java.awt.Color(251, 247, 244));
        ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThongKeMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ThongKe.png"))); // NOI18N
        jLabel5.setText("Thống kê");

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.add(ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 56));

        NhanVien.setBackground(new java.awt.Color(251, 247, 244));
        NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhanVienMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhanVienMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NhanVien.png"))); // NOI18N
        jLabel6.setText("Nhân viên");

        javax.swing.GroupLayout NhanVienLayout = new javax.swing.GroupLayout(NhanVien);
        NhanVien.setLayout(NhanVienLayout);
        NhanVienLayout.setHorizontalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        NhanVienLayout.setVerticalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 270, 56));

        DangXuat.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        DangXuat.setForeground(new java.awt.Color(255, 255, 255));
        DangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DangXuat.setText("Đăng xuất");
        DangXuat.setToolTipText("");
        DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DangXuatMousePressed(evt);
            }
        });
        jPanel4.add(DangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 680, 150, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bản sao Group 1000001512.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 271, 780));

        jPanel2.setBackground(new java.awt.Color(251, 247, 244));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1170, 50));

        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1170, 730));

        jSeparator1.setBackground(new java.awt.Color(223, 219, 216));

        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(723, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 1170, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DatTiecMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatTiecMousePressed
        // TODO add your handling code here:
         TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(ClickedColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_DatTiecMousePressed

    private void TraCuuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraCuuMousePressed
        // TODO add your handling code here:
         TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(ClickedColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_TraCuuMousePressed

    private void DanhMucMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhMucMousePressed
        // TODO add your handling code here:
         TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(ClickedColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_DanhMucMousePressed

    private void ThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMousePressed
        // TODO add your handling code here:
         TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(ClickedColor);
    }//GEN-LAST:event_ThongKeMousePressed

    private void NhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMousePressed
        // TODO add your handling code here:
         TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(ClickedColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_NhanVienMousePressed

    private void TaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoanMousePressed
        // TODO add your handling code here:
         TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(ClickedColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_TaiKhoanMousePressed

    private void TrangChuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChuMousePressed
        // TODO add your handling code here:
         TrangChu.setBackground(ClickedColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_TrangChuMousePressed

    private void DangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DangXuatMousePressed

    private void DatTiecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatTiecMouseClicked
        PartyHallList a = new PartyHallList();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(a).setVisible(true);
    }//GEN-LAST:event_DatTiecMouseClicked

    private void NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMouseClicked
        StaffList sl = new StaffList();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(sl).setVisible(true);

    }//GEN-LAST:event_NhanVienMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DangXuat;
    private javax.swing.JPanel DanhMuc;
    private javax.swing.JPanel DatTiec;
    private javax.swing.JPanel NhanVien;
    private javax.swing.JPanel TaiKhoan;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel TraCuu;
    private javax.swing.JPanel TrangChu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
