package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import dao.NhanVienDAO;
import dao.ThamSoDAO;
import java.awt.Color;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.TaiKhoan;
import model.ThamSo;

/**
 *
 * @author macbookpro
 */
public class Dashboard extends javax.swing.JFrame {

    boolean selected = true;

    /**
     * Creates new form Dashboard
     */
    Color DefaultColor, ClickedColor;

    private Login lg = new Login();

    public Dashboard() {
        initComponents();

        setResizable(false);
        setLocationRelativeTo(null);

        DefaultColor = new Color(251, 247, 244);
        ClickedColor = new Color(238, 230, 226);

        TrangChu.setBackground(ClickedColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);

        jDesktopPane1.removeAll();
        jDesktopPane1.add(new HomePage()).setVisible(true);

        txtfUsernameChange.setText(lg.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogThayDoiQuyDinh = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        checkPhat = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tilePhat = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        tileCoc = new javax.swing.JSpinner();
        btnSaveChange = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        fieldTGChiuPhat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        fieldTGDaiTiec = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnResetPW = new javax.swing.JButton();
        btnSaveNewPW = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtfUsernameChange = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtfConfirm = new javax.swing.JPasswordField();
        txtfPasswordChange = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TaiKhoan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DatTiec = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TrangChu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DanhMuc = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TraCuu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ThongKe = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        NhanVien = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        showDialog = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jSeparator1 = new javax.swing.JSeparator();

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(69, 96, 134));
        jLabel9.setText("Quy định phạt");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setText("Khoảng thời gian chịu phạt");

        checkPhat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        checkPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPhatActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(69, 96, 134));
        jLabel11.setText("Quy định hủy");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Áp dụng quy định phạt");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("Tỉ lệ phạt");

        tilePhat.setName(""); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Tỉ lệ đặt cọc");

        btnSaveChange.setBackground(new java.awt.Color(132, 70, 133));
        btnSaveChange.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSaveChange.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveChange.setText("Lưu");
        btnSaveChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangeActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(69, 96, 134));
        btnCancel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.setAutoscrolls(true);
        btnCancel.setMaximumSize(new java.awt.Dimension(100, 29));
        btnCancel.setMinimumSize(new java.awt.Dimension(100, 29));
        btnCancel.setPreferredSize(new java.awt.Dimension(100, 29));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        fieldTGChiuPhat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldTGChiuPhat.setText("0");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(69, 96, 134));
        jLabel18.setText("Quy định đặt tiệc");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setText("Khoảng thời gian đãi tiệc");

        fieldTGDaiTiec.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldTGDaiTiec.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 123, Short.MAX_VALUE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkPhat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tileCoc)
                            .addComponent(tilePhat)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldTGChiuPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldTGDaiTiec, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveChange, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tilePhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tileCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTGChiuPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTGDaiTiec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveChange, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thay đổi quy định", jPanel3);

        jPanel5.setBackground(new java.awt.Color(238, 230, 226));

        btnResetPW.setBackground(new java.awt.Color(69, 96, 134));
        btnResetPW.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnResetPW.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPW.setText("Làm mới");
        btnResetPW.setAutoscrolls(true);
        btnResetPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPWActionPerformed(evt);
            }
        });

        btnSaveNewPW.setBackground(new java.awt.Color(132, 70, 133));
        btnSaveNewPW.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSaveNewPW.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveNewPW.setText("Lưu");
        btnSaveNewPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewPWActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(69, 96, 134));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Đổi mật khẩu");

        jLabel16.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabel16.setText("Tên tài khoản");

        jLabel17.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabel17.setText("Mật khẩu mới");

        txtfUsernameChange.setEditable(false);
        txtfUsernameChange.setBackground(new java.awt.Color(255, 230, 209));
        txtfUsernameChange.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabel20.setText("Xác nhận mật khẩu mới");

        txtfConfirm.setBackground(new java.awt.Color(247, 235, 226));
        txtfConfirm.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        txtfPasswordChange.setBackground(new java.awt.Color(247, 235, 226));
        txtfPasswordChange.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnResetPW, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveNewPW, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfUsernameChange)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfConfirm)
                    .addComponent(txtfPasswordChange, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnResetPW, btnSaveNewPW});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfUsernameChange, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfPasswordChange, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetPW, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveNewPW))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnResetPW, btnSaveNewPW});

        jTabbedPane1.addTab("Đổi mật khẩu", jPanel5);

        javax.swing.GroupLayout dialogThayDoiQuyDinhLayout = new javax.swing.GroupLayout(dialogThayDoiQuyDinh.getContentPane());
        dialogThayDoiQuyDinh.getContentPane().setLayout(dialogThayDoiQuyDinhLayout);
        dialogThayDoiQuyDinhLayout.setHorizontalGroup(
            dialogThayDoiQuyDinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        dialogThayDoiQuyDinhLayout.setVerticalGroup(
            dialogThayDoiQuyDinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Thay đổi quy định");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 850));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(251, 247, 244));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TaiKhoan.setBackground(new java.awt.Color(251, 247, 244));
        TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaiKhoanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TaiKhoanMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vector.png"))); // NOI18N
        jLabel7.setText("Tài khoản");

        javax.swing.GroupLayout TaiKhoanLayout = new javax.swing.GroupLayout(TaiKhoan);
        TaiKhoan.setLayout(TaiKhoanLayout);
        TaiKhoanLayout.setHorizontalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        TaiKhoanLayout.setVerticalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 270, 56));

        DatTiec.setBackground(new java.awt.Color(251, 247, 244));
        DatTiec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatTiecMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DatTiecMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jLabel2.setText("Đặt tiệc cưới");

        javax.swing.GroupLayout DatTiecLayout = new javax.swing.GroupLayout(DatTiec);
        DatTiec.setLayout(DatTiecLayout);
        DatTiecLayout.setHorizontalGroup(
            DatTiecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatTiecLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        DatTiecLayout.setVerticalGroup(
            DatTiecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatTiecLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.add(DatTiec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 56));

        TrangChu.setBackground(new java.awt.Color(251, 247, 244));
        TrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrangChuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TrangChuMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TrangChu.png"))); // NOI18N
        jLabel1.setText("Trang chủ");

        javax.swing.GroupLayout TrangChuLayout = new javax.swing.GroupLayout(TrangChu);
        TrangChu.setLayout(TrangChuLayout);
        TrangChuLayout.setHorizontalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        TrangChuLayout.setVerticalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.add(TrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 270, 56));

        DanhMuc.setBackground(new java.awt.Color(251, 247, 244));
        DanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DanhMucMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DanhMucMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DanhMuc.png"))); // NOI18N
        jLabel4.setText("Danh mục");

        javax.swing.GroupLayout DanhMucLayout = new javax.swing.GroupLayout(DanhMuc);
        DanhMuc.setLayout(DanhMucLayout);
        DanhMucLayout.setHorizontalGroup(
            DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhMucLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        DanhMucLayout.setVerticalGroup(
            DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhMucLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.add(DanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 270, 56));

        TraCuu.setBackground(new java.awt.Color(251, 247, 244));
        TraCuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TraCuuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TraCuuMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jLabel3.setText("Tra cứu tiệc");

        javax.swing.GroupLayout TraCuuLayout = new javax.swing.GroupLayout(TraCuu);
        TraCuu.setLayout(TraCuuLayout);
        TraCuuLayout.setHorizontalGroup(
            TraCuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TraCuuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        TraCuuLayout.setVerticalGroup(
            TraCuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TraCuuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(TraCuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 56));

        ThongKe.setBackground(new java.awt.Color(251, 247, 244));
        ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThongKeMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ThongKe.png"))); // NOI18N
        jLabel5.setText("Thống kê");

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.add(ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 56));

        NhanVien.setBackground(new java.awt.Color(251, 247, 244));
        NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhanVienMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhanVienMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NhanVien.png"))); // NOI18N
        jLabel6.setText("Nhân viên");

        javax.swing.GroupLayout NhanVienLayout = new javax.swing.GroupLayout(NhanVien);
        NhanVien.setLayout(NhanVienLayout);
        NhanVienLayout.setHorizontalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        NhanVienLayout.setVerticalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 270, 56));

        DangXuat.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        DangXuat.setForeground(new java.awt.Color(255, 255, 255));
        DangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DangXuat.setText("Đăng xuất");
        DangXuat.setToolTipText("");
        DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DangXuatMousePressed(evt);
            }
        });
        jPanel4.add(DangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 680, 150, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bản sao Group 1000001512.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 271, 780));

        jPanel2.setBackground(new java.awt.Color(251, 247, 244));

        showDialog.setText("jButton1");
        showDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(showDialog)
                .addContainerGap(776, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showDialog)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1170, 50));

        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1170, 730));

        jSeparator1.setBackground(new java.awt.Color(223, 219, 216));

        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(723, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 1170, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DatTiecMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatTiecMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(ClickedColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_DatTiecMousePressed

    private void TraCuuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraCuuMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(ClickedColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_TraCuuMousePressed

    private void DanhMucMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhMucMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(ClickedColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_DanhMucMousePressed

    private void ThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(ClickedColor);
    }//GEN-LAST:event_ThongKeMousePressed

    private void NhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(ClickedColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_NhanVienMousePressed

    private void TaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoanMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(ClickedColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_TaiKhoanMousePressed

    private void TrangChuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChuMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(ClickedColor);
        DatTiec.setBackground(DefaultColor);
        TraCuu.setBackground(DefaultColor);
        DanhMuc.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_TrangChuMousePressed

    private void DangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMousePressed
        // TODO add your handling code here:
        Login login = new Login();
        login.show();
        dispose();
    }//GEN-LAST:event_DangXuatMousePressed

    private void DatTiecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatTiecMouseClicked
        // TODO add your handling code here:
        BookingPartyWedding bookingPartyWedding = new BookingPartyWedding();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(bookingPartyWedding).setVisible(true);
    }//GEN-LAST:event_DatTiecMouseClicked

    private void NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMouseClicked
        EmployeeList employee = new EmployeeList();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(employee).setVisible(true);
//    PartyHallList staffList = new PartyHallList();
////    PartyHallTypeList staffList = new PartyHallTypeList();
//       jDesktopPane1.removeAll();
//       jDesktopPane1.add(staffList).setVisible(true);
    }//GEN-LAST:event_NhanVienMouseClicked

    private void DanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhMucMouseClicked
        // TODO add your handling code here:
        ListTable listTable = new ListTable();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(listTable).setVisible(true);
    }//GEN-LAST:event_DanhMucMouseClicked

    private void TraCuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraCuuMouseClicked
        // TODO add your handling code here:
        WeddingPartyLookup lookup = new WeddingPartyLookup();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(lookup).setVisible(true);
    }//GEN-LAST:event_TraCuuMouseClicked

    private void ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMouseClicked
        // TODO add your handling code here:
        RevenueStatistics revenueStatistics = new RevenueStatistics();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(revenueStatistics).setVisible(true);
    }//GEN-LAST:event_ThongKeMouseClicked

    private void showDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDialogActionPerformed
        // TODO add your handling code here:
        boolean isPhat = ThamSoDAO.getInstance().isPhat();
        int tgDatTiec = ThamSoDAO.getInstance().GetThoiGianDatTiec();
        double tilePhatData = ThamSoDAO.getInstance().GetTyLePhat();
        double tileCocData = ThamSoDAO.getInstance().GetTyLeCoc();
        int tgChiuPhat = ThamSoDAO.getInstance().GetThoiGianPhat();

        checkPhat.setSelected(isPhat);
        tileCoc.setValue(tileCocData);
        tilePhat.setValue(tilePhatData);
        fieldTGChiuPhat.setText(String.valueOf(tgChiuPhat));
        fieldTGDaiTiec.setText(String.valueOf(tgDatTiec));
        dialogThayDoiQuyDinh.setSize(400, 550);
        dialogThayDoiQuyDinh.setLocationRelativeTo(null);
        dialogThayDoiQuyDinh.setVisible(true);
    }//GEN-LAST:event_showDialogActionPerformed

    private void checkPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPhatActionPerformed
        // TODO add your handling code here:
        selected = checkPhat.isSelected();
        System.out.println(selected);
    }//GEN-LAST:event_checkPhatActionPerformed

    private void btnSaveChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangeActionPerformed
        // TODO add your handling code here:
        try {
            ThamSoDAO.getInstance().Update(selected, Double.parseDouble(String.valueOf(tilePhat.getValue())), Double.parseDouble(String.valueOf(tileCoc.getValue())), Integer.parseInt(fieldTGChiuPhat.getText()), Integer.parseInt(fieldTGDaiTiec.getText()));
        } catch (Exception e) {
            int ret = JOptionPane.showConfirmDialog(null, "Cập nhật dữ liệu không thành công", "NOTIFICATION", JOptionPane.CLOSED_OPTION);

        }
        int ret = JOptionPane.showConfirmDialog(null, "Cập nhật dữ liệu thất bại", "NOTIFICATION", JOptionPane.CLOSED_OPTION);
        dialogThayDoiQuyDinh.setVisible(false);
    }//GEN-LAST:event_btnSaveChangeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dialogThayDoiQuyDinh.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoanMouseClicked
        // TODO add your handling code here:
        StaffList staffList = new StaffList();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(staffList).setVisible(true);
    }//GEN-LAST:event_TaiKhoanMouseClicked

    private void TrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChuMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.add(new HomePage()).setVisible(true);
    }//GEN-LAST:event_TrangChuMouseClicked

    private void btnResetPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPWActionPerformed
        // TODO add your handling code here:
        txtfUsernameChange.setText(lg.getUsername());
        txtfPasswordChange.setText("");
        txtfConfirm.setText("");
    }//GEN-LAST:event_btnResetPWActionPerformed
    // Chang password 
    private ArrayList<TaiKhoan> lstTaiKhoan = NhanVienDAO.getInstance().SelectAll();

    public void Message(String message, int messageType) {
        JOptionPane jOptionPane = new JOptionPane(message, messageType);
        JDialog dialog = jOptionPane.createDialog(null, "Message");
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }

    public static byte[] hashPassword(String password) throws NoSuchAlgorithmException {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        byte[] encodedPassword = password.getBytes(StandardCharsets.UTF_8);
        byte[] hashedPassword = digest.digest(encodedPassword);
        return hashedPassword;
    }

    private void btnSaveNewPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewPWActionPerformed
        // TODO add your handling code here:
        String newPassword = txtfPasswordChange.getText();
        String pwConfirm = txtfConfirm.getText();
        if (!newPassword.equals(pwConfirm)) {
            Message("Xác nhận mật khẩu chưa chính xác, vui lòng nhập lại", JOptionPane.ERROR_MESSAGE);
            txtfPasswordChange.setText("");
            txtfConfirm.setText("");
        } else {
            try {
                byte[] hassMapPW = hashPassword(newPassword);
                System.out.println(new String(hassMapPW));
                int kq = 0;

                for (TaiKhoan nv : lstTaiKhoan) {
                    if (nv.getUserName().equals(lg.getUsername())) {
                        kq = NhanVienDAO.getInstance().UpdatePassword(new TaiKhoan(nv.getUserName(), new String(hassMapPW), nv.getMaChucVu(), nv.getMaChucVu()));
                    }
                }

                if (kq > 0) {
                    Message("Đổi mật khẩu thành công!", JOptionPane.INFORMATION_MESSAGE);
                    dialogThayDoiQuyDinh.setVisible(false);
                } else {
                    Message("Đổi mật khẩu thất bại!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnSaveNewPWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DangXuat;
    private javax.swing.JPanel DanhMuc;
    private javax.swing.JPanel DatTiec;
    private javax.swing.JPanel NhanVien;
    private javax.swing.JPanel TaiKhoan;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel TraCuu;
    private javax.swing.JPanel TrangChu;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnResetPW;
    private javax.swing.JButton btnSaveChange;
    private javax.swing.JButton btnSaveNewPW;
    private javax.swing.JCheckBox checkPhat;
    private javax.swing.JDialog dialogThayDoiQuyDinh;
    private javax.swing.JTextField fieldTGChiuPhat;
    private javax.swing.JTextField fieldTGDaiTiec;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton showDialog;
    private javax.swing.JSpinner tileCoc;
    private javax.swing.JSpinner tilePhat;
    private javax.swing.JPasswordField txtfConfirm;
    private javax.swing.JPasswordField txtfPasswordChange;
    private javax.swing.JTextField txtfUsernameChange;
    // End of variables declaration//GEN-END:variables
}
