/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.CongViecDAO;
import dao.DichVuDAO;
import dao.EmployeeDAO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.CongViec;
import model.DichVu;
import model.Employee;

/**
 *
 * @author Asus
 */
public class EmployeeList extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeeList
     */
    private DefaultTableModel defaulTableEmployee;
    ArrayList<Employee> lstEmployee = EmployeeDAO.getInstance().SelectAll();
    ArrayList<CongViec> lstCongViec = CongViecDAO.getInstance().SelectAll();
    Map<String, String> mapTenCongViec = new HashMap();

    public EmployeeList() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        CreateTable();
        
        for (CongViec cv : lstCongViec) {
            cbCongViec.addItem(cv.getTenCongViec());
            cbCongViecUD.addItem(cv.getTenCongViec());
            mapTenCongViec.put(cv.getTenCongViec(), cv.getMaCongViec());
        }
        cbGioiTinh.addItem("Nam");
        cbGioiTinh.addItem("Nữ");
        cbGioiTinhUD.addItem("Nam");
        cbGioiTinhUD.addItem("Nữ");
        cbLoaiNV.addItem("Thời vụ");
        cbLoaiNV.addItem("Toàn thời gian");
        cbLoaiNVUD.addItem("Thời vụ");
        cbLoaiNVUD.addItem("Toàn thời gian");

        CreateDataCV();
//        cbMaDV.addItem("Null");
//        cbMaDVUD.addItem("Null");
        for (DichVu dv : lstDichVu) {
            cbMaDV.addItem(dv.getMaDichVu());
            cbMaDVUD.addItem(dv.getMaDichVu());
        }
    }

    private void CreateTable() {
        defaulTableEmployee = (DefaultTableModel) tblEmployee.getModel();
        int i = 0;
        for (Employee e : lstEmployee) {
            defaulTableEmployee.addRow(new Object[]{++i, e.getMaNhanVien(), e.getTenNhanVien(), e.getGioiTinh(), e.getSdt(), e.getTenCongViec(), e.getLoaiNhanVien()});
        }
    }

    private void ReloadDataTable() {
        lstEmployee = EmployeeDAO.getInstance().SelectAll();
        defaulTableEmployee.setRowCount(0);
        CreateTable();
    }

    public void SearchTable() {
        defaulTableEmployee.setRowCount(0);
        defaulTableEmployee = (DefaultTableModel) tblEmployee.getModel();
        int i = 0;
        String value = txtSearchE.getText();
        for (Employee e : lstEmployee) {
            System.out.println();
            if (e.getMaNhanVien().toLowerCase().contains(value.toLowerCase()) || e.getTenNhanVien().toLowerCase().contains(value.toLowerCase()) || e.getTenCongViec().toLowerCase().contains(value.toLowerCase())) {
                defaulTableEmployee.addRow(new Object[]{++i, e.getMaNhanVien(), e.getTenNhanVien(), e.getGioiTinh(), e.getSdt(), e.getTenCongViec(), e.getLoaiNhanVien()});
            }
        }
    }

    public void Message(String message, int messageType) {
        JOptionPane jOptionPane = new JOptionPane(message, messageType);
        JDialog dialog = jOptionPane.createDialog(null, "Message");
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }

    private boolean isValidPhoneNumber(String phoneNumber) {
        // Kiểm tra xem số điện thoại có 10 chữ số và bắt đầu bằng số 0 không
        return phoneNumber.matches("0\\d{9}");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addForm = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCancelE = new javax.swing.JButton();
        btnAddE = new javax.swing.JButton();
        cbCongViec = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbGioiTinh = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbLoaiNV = new javax.swing.JComboBox<>();
        updateForm = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTenNVUD = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnCancelUD = new javax.swing.JButton();
        btnUpdateE = new javax.swing.JButton();
        cbCongViecUD = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtSDTUD = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cbGioiTinhUD = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        cbLoaiNVUD = new javax.swing.JComboBox<>();
        FormCongViec = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblWork = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtSearchCV = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        btnAddCV = new javax.swing.JButton();
        btnDeleteCV = new javax.swing.JButton();
        BackPageCV = new javax.swing.JButton();
        btnUpdateCV = new javax.swing.JButton();
        FormAddCV = new javax.swing.JDialog();
        jPanel17 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtNameWork = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        btnCancelNewCV = new javax.swing.JButton();
        btnAddNewCV = new javax.swing.JButton();
        cbMaDV = new javax.swing.JComboBox<>();
        FormUpdateCV = new javax.swing.JDialog();
        jPanel18 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtNameWorkUD = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        btnCancelCVUD = new javax.swing.JButton();
        btnUpdateCVUD = new javax.swing.JButton();
        cbMaDVUD = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSearchE = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnAddEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        btnUpdateEmployee = new javax.swing.JButton();
        btnDSCongViec = new javax.swing.JButton();

        addForm.setMinimumSize(new java.awt.Dimension(430, 490));
        addForm.setModal(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 96, 134));
        jLabel3.setText("Thêm nhân viên ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Tên nhân viên");

        txtTenNhanVien.setBackground(new java.awt.Color(242, 242, 242));
        txtTenNhanVien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Công việc ");

        btnCancelE.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancelE.setText("Hủy");
        btnCancelE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEActionPerformed(evt);
            }
        });

        btnAddE.setBackground(new java.awt.Color(132, 70, 133));
        btnAddE.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAddE.setForeground(new java.awt.Color(255, 255, 255));
        btnAddE.setText("Thêm ");
        btnAddE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEActionPerformed(evt);
            }
        });

        cbCongViec.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("Số điện thoại");

        txtSDT.setBackground(new java.awt.Color(242, 242, 242));
        txtSDT.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setText("Giới tính");

        cbGioiTinh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Loại");

        cbLoaiNV.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSDT)
                                    .addComponent(cbCongViec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbLoaiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddE, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCancelE, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(43, 43, 43))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbLoaiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout addFormLayout = new javax.swing.GroupLayout(addForm.getContentPane());
        addForm.getContentPane().setLayout(addFormLayout);
        addFormLayout.setHorizontalGroup(
            addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addFormLayout.setVerticalGroup(
            addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        updateForm.setMinimumSize(new java.awt.Dimension(430, 490));
        updateForm.setModal(true);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(69, 96, 134));
        jLabel16.setText("Cập nhật thông tin");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel17.setText("Tên nhân viên");

        txtTenNVUD.setBackground(new java.awt.Color(242, 242, 242));
        txtTenNVUD.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel19.setText("Công việc ");

        btnCancelUD.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancelUD.setText("Hủy");
        btnCancelUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelUDActionPerformed(evt);
            }
        });

        btnUpdateE.setBackground(new java.awt.Color(132, 70, 133));
        btnUpdateE.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnUpdateE.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateE.setText("Cập nhật");
        btnUpdateE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEActionPerformed(evt);
            }
        });

        cbCongViecUD.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel21.setText("Số điện thoại");

        txtSDTUD.setBackground(new java.awt.Color(242, 242, 242));
        txtSDTUD.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel23.setText("Giới tính");

        cbGioiTinhUD.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel25.setText("Loại");

        cbLoaiNVUD.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTenNVUD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSDTUD)
                                        .addComponent(cbCongViecUD, 0, 213, Short.MAX_VALUE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbGioiTinhUD, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbLoaiNVUD, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btnCancelUD, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateE)))
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenNVUD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDTUD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCongViecUD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGioiTinhUD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLoaiNVUD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelUD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout updateFormLayout = new javax.swing.GroupLayout(updateForm.getContentPane());
        updateForm.getContentPane().setLayout(updateFormLayout);
        updateFormLayout.setHorizontalGroup(
            updateFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updateFormLayout.setVerticalGroup(
            updateFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FormCongViec.setMinimumSize(new java.awt.Dimension(1180, 750));
        FormCongViec.setModal(true);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(1180, 730));

        tblWork.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã công việc ", "Tên công việc", "Mã dịch vụ"
            }
        ));
        tblWork.setFocusable(false);
        tblWork.setRowHeight(25);
        tblWork.setSelectionBackground(new java.awt.Color(69, 96, 134));
        tblWork.setShowGrid(false);
        jScrollPane5.setViewportView(tblWork);
        if (tblWork.getColumnModel().getColumnCount() > 0) {
            tblWork.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblWork.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblWork.getColumnModel().getColumn(2).setPreferredWidth(250);
        }
        tblWork.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));

        jPanel14.setBackground(new java.awt.Color(238, 230, 226));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 9.png"))); // NOI18N

        txtSearchCV.setBackground(new java.awt.Color(238, 230, 226));
        txtSearchCV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSearchCV.setBorder(null);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearchCV, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchCV)
                .addContainerGap())
        );

        txtSearchE.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                SearchTable();
            }
            public void removeUpdate(DocumentEvent e) {
                if(txtSearchE.getText().equals("")){
                    defaulTableEmployee.setRowCount(0);
                    CreateTable();
                }else{
                    SearchTable();
                }
            }
            public void insertUpdate(DocumentEvent e) {
                SearchTable();
            }
        });

        txtSearchCV.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                SearchTableCV();
            }
            public void removeUpdate(DocumentEvent e) {
                if(txtSearchCV.getText().equals("")){
                    defaulTableWork.setRowCount(0);
                    CreateDataCV();
                }else{
                    SearchTableCV();
                }
            }
            public void insertUpdate(DocumentEvent e) {
                SearchTableCV();
            }
        });

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(1158, 50));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(69, 96, 134));
        jLabel31.setText("DANH SÁCH CÔNG VIỆC");
        jPanel16.add(jLabel31);

        btnAddCV.setBackground(new java.awt.Color(99, 122, 48));
        btnAddCV.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnAddCV.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAddCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCVActionPerformed(evt);
            }
        });

        btnDeleteCV.setBackground(new java.awt.Color(132, 70, 133));
        btnDeleteCV.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnDeleteCV.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnDeleteCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCVActionPerformed(evt);
            }
        });

        BackPageCV.setBackground(new java.awt.Color(69, 96, 134));
        BackPageCV.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BackPageCV.setForeground(new java.awt.Color(255, 255, 255));
        BackPageCV.setText("Quay lại");
        BackPageCV.setPreferredSize(new java.awt.Dimension(90, 40));
        BackPageCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackPageCVActionPerformed(evt);
            }
        });

        btnUpdateCV.setBackground(new java.awt.Color(248, 189, 141));
        btnUpdateCV.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnUpdateCV.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnUpdateCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(BackPageCV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(btnAddCV, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDeleteCV, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdateCV, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(100, 100, 100))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddCV, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCV, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCV, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackPageCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout FormCongViecLayout = new javax.swing.GroupLayout(FormCongViec.getContentPane());
        FormCongViec.getContentPane().setLayout(FormCongViecLayout);
        FormCongViecLayout.setHorizontalGroup(
            FormCongViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        FormCongViecLayout.setVerticalGroup(
            FormCongViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FormAddCV.setMinimumSize(new java.awt.Dimension(410, 410));
        FormAddCV.setModal(true);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(69, 96, 134));
        jLabel29.setText("Thêm công việc");

        jLabel32.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel32.setText("Tên công việc");

        txtNameWork.setBackground(new java.awt.Color(242, 242, 242));
        txtNameWork.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel34.setText("Mã dịch vụ");

        btnCancelNewCV.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancelNewCV.setText("Hủy");
        btnCancelNewCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewCVActionPerformed(evt);
            }
        });

        btnAddNewCV.setBackground(new java.awt.Color(132, 70, 133));
        btnAddNewCV.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAddNewCV.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewCV.setText("Thêm ");
        btnAddNewCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCVActionPerformed(evt);
            }
        });

        cbMaDV.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNameWork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(btnCancelNewCV, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddNewCV, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameWork, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewCV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelNewCV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout FormAddCVLayout = new javax.swing.GroupLayout(FormAddCV.getContentPane());
        FormAddCV.getContentPane().setLayout(FormAddCVLayout);
        FormAddCVLayout.setHorizontalGroup(
            FormAddCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FormAddCVLayout.setVerticalGroup(
            FormAddCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        FormUpdateCV.setMinimumSize(new java.awt.Dimension(410, 410));
        FormUpdateCV.setModal(true);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jLabel36.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(69, 96, 134));
        jLabel36.setText("Cập nhật công việc");

        jLabel37.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel37.setText("Tên công việc");

        txtNameWorkUD.setBackground(new java.awt.Color(242, 242, 242));
        txtNameWorkUD.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel39.setText("Mã dịch vụ");

        btnCancelCVUD.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancelCVUD.setText("Hủy");
        btnCancelCVUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelCVUDActionPerformed(evt);
            }
        });

        btnUpdateCVUD.setBackground(new java.awt.Color(132, 70, 133));
        btnUpdateCVUD.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnUpdateCVUD.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCVUD.setText("Cập nhật");
        btnUpdateCVUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCVUDActionPerformed(evt);
            }
        });

        cbMaDVUD.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbMaDVUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaDVUDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNameWorkUD, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(btnCancelCVUD, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateCVUD, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMaDVUD, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameWorkUD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMaDVUD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateCVUD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelCVUD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout FormUpdateCVLayout = new javax.swing.GroupLayout(FormUpdateCV.getContentPane());
        FormUpdateCV.getContentPane().setLayout(FormUpdateCVLayout);
        FormUpdateCVLayout.setHorizontalGroup(
            FormUpdateCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FormUpdateCVLayout.setVerticalGroup(
            FormUpdateCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1180, 730));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Employee.png"))); // NOI18N

        tblEmployee.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên ", "Tên nhân viên ", "Giới tính ", "SĐT ", "Tên công việc", "Loại "
            }
        ));
        tblEmployee.setFocusable(false);
        tblEmployee.setRowHeight(25);
        tblEmployee.setSelectionBackground(new java.awt.Color(69, 96, 134));
        tblEmployee.setShowGrid(false);
        jScrollPane1.setViewportView(tblEmployee);
        if (tblEmployee.getColumnModel().getColumnCount() > 0) {
            tblEmployee.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblEmployee.getColumnModel().getColumn(2).setPreferredWidth(150);
        }
        tblEmployee.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));

        jPanel2.setBackground(new java.awt.Color(238, 230, 226));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 9.png"))); // NOI18N

        txtSearchE.setBackground(new java.awt.Color(238, 230, 226));
        txtSearchE.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSearchE.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearchE, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchE)
                .addContainerGap())
        );

        txtSearchE.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                SearchTable();
            }
            public void removeUpdate(DocumentEvent e) {
                if(txtSearchE.getText().equals("")){
                    defaulTableEmployee.setRowCount(0);
                    CreateTable();
                }else{
                    SearchTable();
                }
            }
            public void insertUpdate(DocumentEvent e) {
                SearchTable();
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1158, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(69, 96, 134));
        jLabel13.setText("DANH SÁCH NHÂN VIÊN");
        jPanel5.add(jLabel13);

        btnAddEmployee.setBackground(new java.awt.Color(99, 122, 48));
        btnAddEmployee.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        btnDeleteEmployee.setBackground(new java.awt.Color(132, 70, 133));
        btnDeleteEmployee.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnDeleteEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });

        btnUpdateEmployee.setBackground(new java.awt.Color(248, 189, 141));
        btnUpdateEmployee.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnUpdateEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnUpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmployeeActionPerformed(evt);
            }
        });

        btnDSCongViec.setBackground(new java.awt.Color(255, 167, 149));
        btnDSCongViec.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnDSCongViec.setForeground(new java.awt.Color(255, 255, 255));
        btnDSCongViec.setText("Danh sách công việc");
        btnDSCongViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSCongViecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDSCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDSCongViec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
        addForm.setLocationRelativeTo(null);
        addForm.setVisible(true);
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeActionPerformed
        // TODO add your handling code here:
        int row = tblEmployee.getSelectedRow();
        int[] rows = tblEmployee.getSelectedRows();
        if (row < 0) {
            Message("Vui lòng chọn dữ liệu muốn xoá!", JOptionPane.INFORMATION_MESSAGE);
        } else {

            String mess = "";
            if (rows.length == 1) {
                mess = String.valueOf(tblEmployee.getValueAt(row, 1)) + " ";
            } else {
                for (int r : rows) {
                    mess += String.valueOf(tblEmployee.getValueAt(r, 1)) + " ";
                }
            }

            int x = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá " + mess + "hay không?");
            if (x == JOptionPane.YES_OPTION) {
                int kq = 0;
                if (rows.length == 1) {
                    String maNV = String.valueOf(tblEmployee.getValueAt(row, 1));
                    String tenNV = String.valueOf(tblEmployee.getValueAt(row, 2));
                    String gioiTinh = String.valueOf(tblEmployee.getValueAt(row, 3));
                    String sdt = String.valueOf(tblEmployee.getValueAt(row, 4));
                    String tenCongViec = String.valueOf(tblEmployee.getValueAt(row, 5));
                    String loai = String.valueOf(tblEmployee.getValueAt(row, 6));
                    String maCongViec = mapTenCongViec.get(tenCongViec);
                    try {
                        kq = EmployeeDAO.getInstance().Delete(new Employee(maNV, maCongViec, tenNV, gioiTinh, sdt, loai, tenCongViec));

                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                } else {
                    for (int r : rows) {
                        String maNV = String.valueOf(tblEmployee.getValueAt(r, 1));
                        String tenNV = String.valueOf(tblEmployee.getValueAt(r, 2));
                        String gioiTinh = String.valueOf(tblEmployee.getValueAt(r, 3));
                        String sdt = String.valueOf(tblEmployee.getValueAt(r, 4));
                        String tenCongViec = String.valueOf(tblEmployee.getValueAt(r, 5));
                        String loai = String.valueOf(tblEmployee.getValueAt(r, 6));
                        String maCongViec = mapTenCongViec.get(tenCongViec);

                        try {
                            kq = EmployeeDAO.getInstance().Delete(new Employee(maNV, maCongViec, tenNV, gioiTinh, sdt, loai, tenCongViec));

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        if (kq < 0) {
                            Message("Xoá dữ liệu " + maNV + " - " + tenNV + " thất bại!", JOptionPane.ERROR_MESSAGE);
                        }
                        kq = 1;
                    }
                }
                if (kq > 0) {
                    ReloadDataTable();
                } else {
                    Message("Xoá dữ liệu thất bại!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteEmployeeActionPerformed

    private void btnUpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmployeeActionPerformed
        // TODO add your handling code here:
        int row = tblEmployee.getSelectedRow();
        if (row < 0) {
            Message("Vui lòng chọn dữ liệu muốn chỉnh sửa!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String tenNV = String.valueOf(tblEmployee.getValueAt(row, 2));
            txtTenNVUD.setText(tenNV);
            String gioiTinh = String.valueOf(tblEmployee.getValueAt(row, 3));
            cbGioiTinhUD.setSelectedItem(gioiTinh);
            String sdt = String.valueOf(tblEmployee.getValueAt(row, 4));
            txtSDTUD.setText(sdt);
            String tenCV = String.valueOf(tblEmployee.getValueAt(row, 5));
            cbCongViecUD.setSelectedItem(tenCV);
            String loai = String.valueOf(tblEmployee.getValueAt(row, 6));
            cbLoaiNVUD.setSelectedItem(loai);
            updateForm.setLocationRelativeTo(null);
            updateForm.setVisible(true);
        }
    }//GEN-LAST:event_btnUpdateEmployeeActionPerformed

    private void btnCancelEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEActionPerformed
        // TODO add your handling code here:
        addForm.setVisible(false);
    }//GEN-LAST:event_btnCancelEActionPerformed

    private void btnAddEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEActionPerformed
        // TODO add your handling code here:
        if (txtTenNhanVien.getText().equals("") || txtSDT.getText().equals("")) {
            Message("Vui lòng nhập đầy đủ dữ liệu!", JOptionPane.WARNING_MESSAGE);
        } else if (!isValidPhoneNumber(txtSDT.getText())) {
            Message("Vui lòng nhập SĐT có 10 chữ số và bắt đầu là số 0!", JOptionPane.WARNING_MESSAGE);
        } else {
            String maNV = String.valueOf(Integer.parseInt(String.valueOf(defaulTableEmployee.getValueAt(defaulTableEmployee.getRowCount() - 1, 1)).substring(2)) + 1);
            switch (maNV.length()) {
                case 1:
                    maNV = "NV000" + maNV;
                    break;
                case 2:
                    maNV = "NV00" + maNV;
                    break;
                case 3:
                    maNV = "NV0" + maNV;
                    break;
                case 4:
                    maNV = "NV" + maNV;
                    break;
            }
            int kq = 0;

            try {
                String tenNhanVien = txtTenNhanVien.getText();
                String gioiTinh = cbGioiTinh.getSelectedItem().toString();
                String sdt = txtSDT.getText();
                String tenCongViec = cbCongViec.getSelectedItem().toString();
                String loai = cbLoaiNV.getSelectedItem().toString();
                String maCongViec = mapTenCongViec.get(tenCongViec);

                boolean check = true;
                for (Employee e : lstEmployee) {
                    if (e.getMaNhanVien().equals(maNV)) {
                        check = false;
                    }
                }
                if (!check) {
                    Message("Tài khoản đã tồn tại, vui lòng nhập lại!", JOptionPane.WARNING_MESSAGE);
                    txtTenNhanVien.setText("");
                    return;
                } else {
                    kq = EmployeeDAO.getInstance().Insert(new Employee(maNV, maCongViec, tenNhanVien, gioiTinh, sdt, loai, tenCongViec));
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            if (kq != 0) {
                addForm.setVisible(false);
                ReloadDataTable();
                txtTenNhanVien.setText("");
                txtSDT.setText("");
            } else {
                Message("Lỗi! Thêm dữ liệu thất bại. Vui lòng nhập lại dữ liệu.", JOptionPane.ERROR_MESSAGE);
                txtTenNhanVien.setText("");
                txtSDT.setText("");
            }
        }
    }//GEN-LAST:event_btnAddEActionPerformed

    private void btnCancelUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelUDActionPerformed
        // TODO add your handling code here:
        updateForm.setVisible(false);
    }//GEN-LAST:event_btnCancelUDActionPerformed

    private void btnUpdateEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEActionPerformed
        // TODO add your handling code here:
        int row = tblEmployee.getSelectedRow();

        String maNV = String.valueOf(tblEmployee.getValueAt(row, 1));
        String tenNhanVien = txtTenNVUD.getText();
        String gioiTinh = cbGioiTinhUD.getSelectedItem().toString();
        String sdt = txtSDTUD.getText();
        String tenCongViec = cbCongViecUD.getSelectedItem().toString();
        String loai = cbLoaiNVUD.getSelectedItem().toString();
        String maCongViec = mapTenCongViec.get(tenCongViec);
        System.out.println("adsfad" + maCongViec);
        int kq = 0;

        kq = EmployeeDAO.getInstance().Update(new Employee(maNV, maCongViec, tenNhanVien, gioiTinh, sdt, loai, tenCongViec));

        if (kq > 0) {
            updateForm.setVisible(false);
            ReloadDataTable();
        } else {
            updateForm.setVisible(false);
            Message("Chỉnh sửa dữ liệu thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateEActionPerformed

    // Danh sách Công việc 
    private DefaultTableModel defaulTableWork;
    private ArrayList<DichVu> lstDichVu = DichVuDAO.getInstance().SelectAll();

    public void CreateDataCV() {
        defaulTableWork = (DefaultTableModel) tblWork.getModel();
        int i = 0;
        for (CongViec cv : lstCongViec) {
            defaulTableWork.addRow(new Object[]{++i, cv.getMaCongViec(), cv.getTenCongViec(), cv.getMaDichVu()});
        }
    }

    public void SearchTableCV() {
        defaulTableWork.setRowCount(0);
        defaulTableWork = (DefaultTableModel) tblWork.getModel();
        int i = 0;
        String value = txtSearchCV.getText();
        for (CongViec x : lstCongViec) {
            System.out.println();
            if (x.getMaCongViec().toLowerCase().contains(value.toLowerCase()) || x.getTenCongViec().toLowerCase().contains(value.toLowerCase())) {
                defaulTableWork.addRow(new Object[]{++i, x.getMaCongViec(), x.getTenCongViec(), x.getMaDichVu()});
            }
        }
    }

    public void ReloadDataTableCV() {
        lstCongViec = CongViecDAO.getInstance().SelectAll();
        defaulTableWork.setRowCount(0);
        CreateDataCV();
    }

    private void btnDSCongViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSCongViecActionPerformed
        // TODO add your handling code here:
        FormCongViec.setLocationRelativeTo(null);
        FormCongViec.setVisible(true);

    }//GEN-LAST:event_btnDSCongViecActionPerformed

    private void btnAddCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCVActionPerformed
        // TODO add your handling code here:
        FormAddCV.setLocationRelativeTo(null);
        FormAddCV.setVisible(true);
    }//GEN-LAST:event_btnAddCVActionPerformed

    private void btnDeleteCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCVActionPerformed
        // TODO add your handling code here:
        int row = tblWork.getSelectedRow();
        int[] rows = tblWork.getSelectedRows();
        if (row < 0) {
            Message("Vui lòng chọn dữ liệu muốn xoá!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String mess = "";
            if (rows.length == 1) {
                mess = String.valueOf(tblWork.getValueAt(row, 1)) + " ";
            } else {
                for (int r : rows) {
                    mess += String.valueOf(tblWork.getValueAt(r, 1)) + " ";
                }
            }

            int x = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá " + mess + "hay không?");
            if (x == JOptionPane.YES_OPTION) {
                int kq = 0;
                if (rows.length == 1) {
                    String maCV = String.valueOf(tblWork.getValueAt(row, 1));
                    String tenCV = String.valueOf(tblWork.getValueAt(row, 2));
                    String maDV = String.valueOf(tblWork.getValueAt(row, 3));
                    try {
                        kq = CongViecDAO.getInstance().Delete(new CongViec(maCV, tenCV, maDV));

                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                } else {
                    for (int r : rows) {
                        String maCV = String.valueOf(tblWork.getValueAt(r, 1));
                        String tenCV = String.valueOf(tblWork.getValueAt(r, 2));
                        String maDV = String.valueOf(tblWork.getValueAt(r, 3));
                        try {
                            kq = CongViecDAO.getInstance().Delete(new CongViec(maCV, tenCV, maDV));

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        if (kq < 0) {
                            Message("Xoá dữ liệu " + maCV + " - " + tenCV + " thất bại!", JOptionPane.ERROR_MESSAGE);
                        }
                        kq = 1;
                    }
                }
                if (kq > 0) {
                    ReloadDataTableCV();
                } else {
                    Message("Xoá dữ liệu thất bại!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteCVActionPerformed

    private void btnUpdateCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCVActionPerformed
        // TODO add your handling code here:
        int row = tblWork.getSelectedRow();
        if (row < 0) {
            Message("Vui lòng chọn dữ liệu muốn chỉnh sửa!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String maCV = String.valueOf(tblWork.getValueAt(row, 1));
            String tenCV = String.valueOf(tblWork.getValueAt(row, 2));
            String maDV = String.valueOf(tblWork.getValueAt(row, 3));
            txtNameWorkUD.setText(tenCV);
            cbMaDVUD.setSelectedItem(maDV);
            FormUpdateCV.setLocationRelativeTo(null);
            FormUpdateCV.setVisible(true);
        }
    }//GEN-LAST:event_btnUpdateCVActionPerformed

    private void btnCancelNewCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewCVActionPerformed
        // TODO add your handling code here:
        FormAddCV.setVisible(false);
    }//GEN-LAST:event_btnCancelNewCVActionPerformed

    private void btnAddNewCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCVActionPerformed
        // TODO add your handling code here:
        if (txtNameWork.getText().equals("")) {
            Message("Vui lòng nhập đầy đủ dữ liệu!", JOptionPane.WARNING_MESSAGE);
        } else {
            String maCV = String.valueOf(Integer.parseInt(String.valueOf(defaulTableWork.getValueAt(defaulTableWork.getRowCount() - 1, 1)).substring(3)) + 1);
            switch (maCV.length()) {
                case 1:
                    maCV = "CVC00" + maCV;
                    break;
                case 2:
                    maCV = "CVC0" + maCV;
                    break;
                case 3:
                    maCV = "CVC" + maCV;
                    break;
            }
            int kq = 0;
            try {
                String tenCV = txtNameWork.getText();
                String maDV = cbMaDV.getSelectedItem().toString();
                boolean check = true;
                for (CongViec cv : lstCongViec) {
                    if (cv.getTenCongViec().equals(tenCV)) {
                        check = false;
                    }
                }
                if (!check) {
                    Message("Công việc đã tồn tại, vui lòng nhập lại!", JOptionPane.WARNING_MESSAGE);
                    txtNameWork.setText("");
                    return;
                } else {
//                    if(cbMaDV.getSelectedIndex() == 0)
//                        kq = CongViecDAO.getInstance().Insert(new CongViec(maCV, tenCV, ""));
//                    else
                        kq = CongViecDAO.getInstance().Insert(new CongViec(maCV, tenCV, maDV));
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            if (kq != 0) {
                FormAddCV.setVisible(false);
                ReloadDataTableCV();
                txtNameWork.setText("");
            } else {
                Message("Lỗi! Thêm dữ liệu thất bại. Vui lòng nhập lại dữ liệu.", JOptionPane.ERROR_MESSAGE);
                txtNameWork.setText("");
            }
        }
    }//GEN-LAST:event_btnAddNewCVActionPerformed

    private void btnCancelCVUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelCVUDActionPerformed
        // TODO add your handling code here:
        FormUpdateCV.setVisible(false);
    }//GEN-LAST:event_btnCancelCVUDActionPerformed

    private void btnUpdateCVUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCVUDActionPerformed
        // TODO add your handling code here:
        int row = tblWork.getSelectedRow();
        String maCV = String.valueOf(tblWork.getValueAt(row, 1));
        String tenCV = txtNameWorkUD.getText();
        String maDV = cbMaDVUD.getSelectedItem().toString();

        int kq = 0;
//        if(cbMaDVUD.getSelectedIndex() == 0)
//            kq = CongViecDAO.getInstance().Update(new CongViec(maCV, tenCV, ""));
//        else
            
            kq = CongViecDAO.getInstance().Update(new CongViec(maCV, tenCV, maDV));

        if (kq > 0) {
            FormUpdateCV.setVisible(false);
            ReloadDataTableCV();
        } else {
            FormUpdateCV.setVisible(false);
            Message("Chỉnh sửa dữ liệu thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateCVUDActionPerformed

    private void BackPageCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackPageCVActionPerformed
        // TODO add your handling code here:
        FormCongViec.setVisible(false);
    }//GEN-LAST:event_BackPageCVActionPerformed

    private void cbMaDVUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaDVUDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaDVUDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackPageCV;
    private javax.swing.JDialog FormAddCV;
    private javax.swing.JDialog FormCongViec;
    private javax.swing.JDialog FormUpdateCV;
    private javax.swing.JDialog addForm;
    private javax.swing.JButton btnAddCV;
    private javax.swing.JButton btnAddE;
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnAddNewCV;
    private javax.swing.JButton btnCancelCVUD;
    private javax.swing.JButton btnCancelE;
    private javax.swing.JButton btnCancelNewCV;
    private javax.swing.JButton btnCancelUD;
    private javax.swing.JButton btnDSCongViec;
    private javax.swing.JButton btnDeleteCV;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnUpdateCV;
    private javax.swing.JButton btnUpdateCVUD;
    private javax.swing.JButton btnUpdateE;
    private javax.swing.JButton btnUpdateEmployee;
    private javax.swing.JComboBox<String> cbCongViec;
    private javax.swing.JComboBox<String> cbCongViecUD;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbGioiTinhUD;
    private javax.swing.JComboBox<String> cbLoaiNV;
    private javax.swing.JComboBox<String> cbLoaiNVUD;
    private javax.swing.JComboBox<String> cbMaDV;
    private javax.swing.JComboBox<String> cbMaDVUD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblWork;
    private javax.swing.JTextField txtNameWork;
    private javax.swing.JTextField txtNameWorkUD;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSDTUD;
    private javax.swing.JTextField txtSearchCV;
    private javax.swing.JTextField txtSearchE;
    private javax.swing.JTextField txtTenNVUD;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JDialog updateForm;
    // End of variables declaration//GEN-END:variables
}
