/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.LoaiSanhDAO;
import dao.SanhDAO;
import java.awt.Color;
import java.awt.Font;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import model.LoaiSanh;
import model.Sanh;

/**
 *
 * @author macbookpro
 */
public class PartyHallList extends javax.swing.JInternalFrame {

    private DefaultTableModel defaultTableModelHall;
    private ArrayList<Sanh> sanhs = SanhDAO.getInstance().SelectAll();
    private Map<String, String> mapMaLoaiSanh = new HashMap<>();
    private Map<String, String> mapDonGiaBanToiThieu = new HashMap<>();
    private ArrayList<LoaiSanh> loaiSanhs = LoaiSanhDAO.getInstance().SelectAll();
    private NumberFormat currencyFormatVN = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));


    /**
     * Creates new form WorkingTimeList
     */
    public PartyHallList() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        CreateDataTable();

        for (LoaiSanh x : loaiSanhs) {
            mapMaLoaiSanh.put(x.getTenLoaiSanh(), x.getMaLoaiSanh());
            mapDonGiaBanToiThieu.put(x.getTenLoaiSanh(), String.valueOf(x.getDonGiaBanToiThieu()));
            cbxLoaiSanh.addItem(x.getTenLoaiSanh());
            cbxLoaiSanhValue.addItem(x.getTenLoaiSanh());
        }
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER); // Set the desired horizontal alignment
        Table_Hall.getColumnModel().getColumn(0).setCellRenderer(renderer);

    }

    public void CreateDataTable() {
        defaultTableModelHall = (DefaultTableModel) Table_Hall.getModel();
        int i = 0;
        for (Sanh x : sanhs) {
            defaultTableModelHall.addRow(new Object[]{++i, x.getMaSanh(), x.getTenSanh(), x.getTenLoaiSanh(),
                x.getSoLuongBanToiDa(), currencyFormatVN.format(x.getDonGiaBanToiThieu()), x.getGhiChu()});
        }
    }

    public void SearchTable() {
        defaultTableModelHall.setRowCount(0);
        defaultTableModelHall = (DefaultTableModel) Table_Hall.getModel();
        int i = 0;
        String value = txfSearchTable.getText();
        for (Sanh x : sanhs) {
            System.out.println();
            if (x.getMaSanh().toLowerCase().contains(value.toLowerCase()) || x.getTenLoaiSanh().toLowerCase().contains(value.toLowerCase())
                    || x.getTenSanh().toLowerCase().contains(value.toLowerCase())) {
                defaultTableModelHall.addRow(new Object[]{++i, x.getMaSanh(), x.getTenSanh(), x.getTenLoaiSanh(),
                    x.getSoLuongBanToiDa(), currencyFormatVN.format(x.getDonGiaBanToiThieu()), x.getGhiChu()});
            }
        }
    }

    public void ReloadDataTable() {
        sanhs = SanhDAO.getInstance().SelectAll();
        defaultTableModelHall.setRowCount(0);
        CreateDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_Hall_List_Dialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfTenSanh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txfDonGiaToiThieu = new javax.swing.JTextField();
        HuyAdd_Hall_List_Dialog = new javax.swing.JButton();
        ThemAdd_Hall_List_Dialog = new javax.swing.JButton();
        cbxLoaiSanh = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txfSoLuongBanToiDa = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txaGhiChu = new javax.swing.JTextField();
        Edit_Hall_List_Dialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txfTenSanhValue = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txfDonGiaToiThieuValue = new javax.swing.JTextField();
        HuyEdit_Hall_List_Dialog = new javax.swing.JButton();
        ThemEdit_Edit_List_Dialog = new javax.swing.JButton();
        cbxLoaiSanhValue = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txfSoLuongBanToiDaValue = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txaGhiChuValue = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAddHall = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Hall = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnDeleteHall = new javax.swing.JButton();
        btnEditHall = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txfSearchTable = new javax.swing.JTextField();
        BackPage3 = new javax.swing.JButton();

        Add_Hall_List_Dialog.setMinimumSize(new java.awt.Dimension(531, 490));
        Add_Hall_List_Dialog.setModal(true);
        Add_Hall_List_Dialog.setSize(new java.awt.Dimension(860, 500));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(508, 800));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(69, 96, 134));
        jLabel4.setText("Tiếp nhận sảnh");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setText("Tên Sảnh");

        txfTenSanh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Loại Sảnh");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("Đơn gia bàn tối thiểu");

        txfDonGiaToiThieu.setEditable(false);
        txfDonGiaToiThieu.setBackground(new java.awt.Color(255, 255, 255));
        txfDonGiaToiThieu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txfDonGiaToiThieu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfDonGiaToiThieu.setText("0");

        HuyAdd_Hall_List_Dialog.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        HuyAdd_Hall_List_Dialog.setText("Hủy");
        HuyAdd_Hall_List_Dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyAdd_Hall_List_DialogActionPerformed(evt);
            }
        });

        ThemAdd_Hall_List_Dialog.setBackground(new java.awt.Color(132, 70, 133));
        ThemAdd_Hall_List_Dialog.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        ThemAdd_Hall_List_Dialog.setForeground(new java.awt.Color(255, 255, 255));
        ThemAdd_Hall_List_Dialog.setText("Thêm ");
        ThemAdd_Hall_List_Dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemAdd_Hall_List_DialogActionPerformed(evt);
            }
        });

        cbxLoaiSanh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbxLoaiSanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiSanhActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Số lượng bàn tối đa");

        txfSoLuongBanToiDa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txfSoLuongBanToiDa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfSoLuongBanToiDa.setText("0");
        txfSoLuongBanToiDa.setToolTipText("");
        txfSoLuongBanToiDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSoLuongBanToiDaActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel25.setText("Ghi chú");

        txaGhiChu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(HuyAdd_Hall_List_Dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ThemAdd_Hall_List_Dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txaGhiChu)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfDonGiaToiThieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                            .addComponent(txfTenSanh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfSoLuongBanToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbxLoaiSanh, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfTenSanh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxLoaiSanh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfDonGiaToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfSoLuongBanToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txaGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemAdd_Hall_List_Dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HuyAdd_Hall_List_Dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Add_Hall_List_DialogLayout = new javax.swing.GroupLayout(Add_Hall_List_Dialog.getContentPane());
        Add_Hall_List_Dialog.getContentPane().setLayout(Add_Hall_List_DialogLayout);
        Add_Hall_List_DialogLayout.setHorizontalGroup(
            Add_Hall_List_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        Add_Hall_List_DialogLayout.setVerticalGroup(
            Add_Hall_List_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        Edit_Hall_List_Dialog.setMinimumSize(new java.awt.Dimension(531, 490));
        Edit_Hall_List_Dialog.setModal(true);
        Edit_Hall_List_Dialog.setSize(new java.awt.Dimension(850, 500));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(850, 500));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(69, 96, 134));
        jLabel11.setText("Chỉnh sửa sảnh ");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Tên Sảnh");

        txfTenSanhValue.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setText("Loại Sảnh");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setText("Đơn gia bàn tối thiểu");

        txfDonGiaToiThieuValue.setEditable(false);
        txfDonGiaToiThieuValue.setBackground(new java.awt.Color(255, 255, 255));
        txfDonGiaToiThieuValue.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txfDonGiaToiThieuValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfDonGiaToiThieuValue.setText("0");

        HuyEdit_Hall_List_Dialog.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        HuyEdit_Hall_List_Dialog.setText("Hủy");
        HuyEdit_Hall_List_Dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyEdit_Hall_List_DialogActionPerformed(evt);
            }
        });

        ThemEdit_Edit_List_Dialog.setBackground(new java.awt.Color(132, 70, 133));
        ThemEdit_Edit_List_Dialog.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        ThemEdit_Edit_List_Dialog.setForeground(new java.awt.Color(255, 255, 255));
        ThemEdit_Edit_List_Dialog.setText("Thêm ");
        ThemEdit_Edit_List_Dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemEdit_Edit_List_DialogActionPerformed(evt);
            }
        });

        cbxLoaiSanhValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiSanhValueActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setText("Số lượng bàn tối đa");

        txfSoLuongBanToiDaValue.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txfSoLuongBanToiDaValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfSoLuongBanToiDaValue.setText("0");
        txfSoLuongBanToiDaValue.setToolTipText("");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel26.setText("Ghi chú");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(HuyEdit_Hall_List_Dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ThemEdit_Edit_List_Dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txaGhiChuValue)
                                .addComponent(txfDonGiaToiThieuValue, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txfTenSanhValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txfSoLuongBanToiDaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxLoaiSanhValue, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfTenSanhValue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxLoaiSanhValue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfDonGiaToiThieuValue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfSoLuongBanToiDaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txaGhiChuValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemEdit_Edit_List_Dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HuyEdit_Hall_List_Dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Edit_Hall_List_DialogLayout = new javax.swing.GroupLayout(Edit_Hall_List_Dialog.getContentPane());
        Edit_Hall_List_Dialog.getContentPane().setLayout(Edit_Hall_List_DialogLayout);
        Edit_Hall_List_DialogLayout.setHorizontalGroup(
            Edit_Hall_List_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Edit_Hall_List_DialogLayout.setVerticalGroup(
            Edit_Hall_List_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(1170, 730));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 730));

        btnAddHall.setBackground(new java.awt.Color(99, 122, 48));
        btnAddHall.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnAddHall.setForeground(new java.awt.Color(255, 255, 255));
        btnAddHall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAddHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHallActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hall.png"))); // NOI18N

        Table_Hall.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Table_Hall.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sảnh", "Tên Sảnh", "Loại Sảnh", "Số lượng bàn tối đa", "Đơn giá tối thiểu", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Hall.setFocusable(false);
        Table_Hall.setRowHeight(25);
        Table_Hall.setSelectionBackground(new java.awt.Color(69, 96, 134));
        jScrollPane1.setViewportView(Table_Hall);
        if (Table_Hall.getColumnModel().getColumnCount() > 0) {
            Table_Hall.getColumnModel().getColumn(0).setMinWidth(50);
            Table_Hall.getColumnModel().getColumn(0).setPreferredWidth(50);
            Table_Hall.getColumnModel().getColumn(0).setMaxWidth(50);
            Table_Hall.getColumnModel().getColumn(0).setCellRenderer(null);
            Table_Hall.getColumnModel().getColumn(1).setMinWidth(100);
            Table_Hall.getColumnModel().getColumn(1).setPreferredWidth(100);
            Table_Hall.getColumnModel().getColumn(1).setMaxWidth(20);
        }
        Table_Hall.getTableHeader().setFont(new Font("Arial", Font.BOLD, 16));
        Table_Hall.getTableHeader().setOpaque(false);
        Table_Hall.getTableHeader().setBackground(new Color(243,246,249));
        Table_Hall.setDefaultEditor(Object.class, null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(69, 96, 134));
        jLabel13.setText("DANH SÁCH SẢNH");
        jPanel5.add(jLabel13);

        btnDeleteHall.setBackground(new java.awt.Color(132, 70, 133));
        btnDeleteHall.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnDeleteHall.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteHall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnDeleteHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHallActionPerformed(evt);
            }
        });

        btnEditHall.setBackground(new java.awt.Color(248, 189, 141));
        btnEditHall.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnEditHall.setForeground(new java.awt.Color(255, 255, 255));
        btnEditHall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnEditHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditHallActionPerformed(evt);
            }
        });

        jPanel35.setBackground(new java.awt.Color(238, 230, 226));
        jPanel35.setPreferredSize(new java.awt.Dimension(260, 50));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 9.png"))); // NOI18N

        txfSearchTable.setBackground(new java.awt.Color(238, 230, 226));
        txfSearchTable.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txfSearchTable.setBorder(null);
        txfSearchTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSearchTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfSearchTable, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel28)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfSearchTable)
                .addContainerGap())
        );

        txfSearchTable.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                SearchTable();
            }
            public void removeUpdate(DocumentEvent e) {
                if(txfSearchTable.getText().equals("")){
                    defaultTableModelHall.setRowCount(0);
                    CreateDataTable();
                }else{
                    SearchTable();
                }
            }
            public void insertUpdate(DocumentEvent e) {
                SearchTable();
            }
        });

        BackPage3.setBackground(new java.awt.Color(69, 96, 134));
        BackPage3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BackPage3.setForeground(new java.awt.Color(255, 255, 255));
        BackPage3.setText("Quay lại");
        BackPage3.setPreferredSize(new java.awt.Dimension(90, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BackPage3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAddHall, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteHall, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditHall, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteHall, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddHall, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditHall, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackPage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Message(String message, int messageType) {
        JOptionPane jOptionPane = new JOptionPane(message, messageType);
        JDialog dialog = jOptionPane.createDialog(null, "Message");
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }

    private void btnAddHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHallActionPerformed
        // TODO add your handling code here
        Add_Hall_List_Dialog.setLocationRelativeTo(null);
        Add_Hall_List_Dialog.setVisible(true);

    }//GEN-LAST:event_btnAddHallActionPerformed

    private void btnDeleteHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHallActionPerformed
        // TODO add your handling code here:
        int row = Table_Hall.getSelectedRow();
        int[] rows = Table_Hall.getSelectedRows();
        if (row < 0) {
            Message("Vui lòng chọn dữ liệu muốn xoá!", JOptionPane.INFORMATION_MESSAGE);
        } else {

            String mess = "";
            if (rows.length == 1) {
                mess = String.valueOf(Table_Hall.getValueAt(row, 1)) + " ";
            } else {
                for (int r : rows) {
                    mess += String.valueOf(Table_Hall.getValueAt(r, 1)) + " ";
                }
            }

            int x = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá " + mess + "hay không?");
            if (x == JOptionPane.YES_OPTION) {
                int kq = 0;
                if (rows.length == 1) {
                    String maSanh = String.valueOf(Table_Hall.getValueAt(row, 1));
                    String tenSanh = String.valueOf(Table_Hall.getValueAt(row, 2));
                    String tenLoaiSanh = String.valueOf(Table_Hall.getValueAt(row, 3));
                    String maLoaiSanh = mapMaLoaiSanh.get(tenLoaiSanh);
                    int soLuongBanToiDa = Integer.parseInt(String.valueOf(Table_Hall.getValueAt(row, 4)));
                    int donGiaBanToiThieu = 0;
                    try {
                        donGiaBanToiThieu = Integer.parseInt(String.valueOf(currencyFormatVN.parse(String.valueOf(Table_Hall.getValueAt(row, 5)))));
                    } catch (ParseException ex) {
                        Logger.getLogger(PartyHallList.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    String ghiChu = String.valueOf(Table_Hall.getValueAt(row, 6));

                    try {
                        kq = SanhDAO.getInstance().Delete(new Sanh(maSanh, maLoaiSanh, tenSanh,
                                soLuongBanToiDa, tenLoaiSanh, donGiaBanToiThieu, ghiChu));

                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                } else {
                    for (int r : rows) {
                        String maSanh = String.valueOf(Table_Hall.getValueAt(r, 1));
                        String tenSanh = String.valueOf(Table_Hall.getValueAt(r, 2));
                        String tenLoaiSanh = String.valueOf(Table_Hall.getValueAt(r, 3));
                        String maLoaiSanh = mapMaLoaiSanh.get(tenLoaiSanh);
                        int soLuongBanToiDa = Integer.parseInt(String.valueOf(Table_Hall.getValueAt(r, 4)));
                        int donGiaBanToiThieu = 0;
                        try {
                            donGiaBanToiThieu = Integer.parseInt(String.valueOf(currencyFormatVN.parse(String.valueOf(Table_Hall.getValueAt(row, 5)))));
                        } catch (ParseException ex) {
                            Logger.getLogger(PartyHallList.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        String ghiChu = String.valueOf(Table_Hall.getValueAt(r, 6));

                        try {
                            kq = SanhDAO.getInstance().Delete(new Sanh(maSanh, maLoaiSanh, tenSanh,
                                    soLuongBanToiDa, tenLoaiSanh, donGiaBanToiThieu, ghiChu));

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        if (kq < 0) {
                            Message("Xoá dữ liệu" + maSanh + "thất bại!", JOptionPane.ERROR_MESSAGE);
                        }
                        kq = 1;
                    }
                }
                if (kq > 0) {
                    ReloadDataTable();
                } else {
                    Message("Xoá dữ liệu thất bại!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteHallActionPerformed

    private void btnEditHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditHallActionPerformed
        // TODO add your handling code here:
        int row = Table_Hall.getSelectedRow();
        if (row < 0) {
            Message("Vui lòng chọn dữ liệu muốn chỉnh sửa!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String tenSanh = String.valueOf(Table_Hall.getValueAt(row, 2));
            String tenLoaiSanh = String.valueOf(Table_Hall.getValueAt(row, 3));
            String soLuongBanToiDa = String.valueOf(Table_Hall.getValueAt(row, 4));
            String ghiChu = String.valueOf(Table_Hall.getValueAt(row, 6));

            txfTenSanhValue.setText(tenSanh);
            cbxLoaiSanhValue.setSelectedItem(tenLoaiSanh);
            txfSoLuongBanToiDaValue.setText(soLuongBanToiDa);
            txaGhiChuValue.setText(ghiChu);

            Edit_Hall_List_Dialog.setLocationRelativeTo(null);
            Edit_Hall_List_Dialog.setVisible(true);
        }

    }//GEN-LAST:event_btnEditHallActionPerformed

    private void txfSearchTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSearchTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSearchTableActionPerformed

    private void HuyAdd_Hall_List_DialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyAdd_Hall_List_DialogActionPerformed
        // TODO add your handling code here:
        Add_Hall_List_Dialog.setVisible(false);

    }//GEN-LAST:event_HuyAdd_Hall_List_DialogActionPerformed

    private void ThemAdd_Hall_List_DialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemAdd_Hall_List_DialogActionPerformed
        // TODO add your handling code here:
        if (txfTenSanh.getText().equals("")) {
            Message("Vui lòng nhập dữ liệu!", JOptionPane.WARNING_MESSAGE);
        }else if (Integer.parseInt(txfSoLuongBanToiDa.getText()) <= 0) {
                System.out.println("abc");
                Message("Số lượng bàn tối đa phải lớn hơn 0", JOptionPane.WARNING_MESSAGE);
            } else {
                String maSanh = String.valueOf(SanhDAO.getInstance().GetID() + 1);
                switch (maSanh.length()) {
                    case 1:
                        maSanh = "SN000" + maSanh;
                        break;
                    case 2:
                        maSanh = "SN00" + maSanh;
                        break;
                    case 3:
                        maSanh = "SN0" + maSanh;
                        break;
                    case 4:
                        maSanh = "SN" + maSanh;
                        break;
                }
                int kq = 0;
                try {
                    String tenSanh = txfTenSanh.getText();
                    String tenLoaiSanh = cbxLoaiSanh.getSelectedItem().toString();
                    String maLoaiSanh = mapMaLoaiSanh.get(tenLoaiSanh);
                    System.out.println(tenLoaiSanh + " " + maLoaiSanh);
                    int soLuongBanToiDa = Integer.parseInt(txfSoLuongBanToiDa.getText());
                    int donGiaBanToiThieu = Integer.parseInt(txfDonGiaToiThieu.getText());
                    String ghiChu = txaGhiChu.getText();
                    System.out.println(ghiChu);
                    kq = SanhDAO.getInstance().Insert(new Sanh(maSanh, maLoaiSanh, tenSanh, soLuongBanToiDa, tenLoaiSanh, donGiaBanToiThieu, ghiChu));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                if (kq != 0) {
                    Add_Hall_List_Dialog.setVisible(false);
                    ReloadDataTable();
                    txfTenSanh.setText("");
                    txfDonGiaToiThieu.setText(mapDonGiaBanToiThieu.get(cbxLoaiSanh.getSelectedItem()));
                    txfSoLuongBanToiDa.setText("0");
                    txaGhiChu.setText("");
                    Message("Thêm dữ liệu thành công", JOptionPane.WARNING_MESSAGE);

                } else {
                    Message("Lỗi! Thêm dữ liệu thất bại. Vui lòng nhập lại dữ liệu.", JOptionPane.ERROR_MESSAGE);
                    txfTenSanh.setText("");
                    txfDonGiaToiThieu.setText(mapDonGiaBanToiThieu.get(cbxLoaiSanh.getSelectedItem()));
                    txfSoLuongBanToiDa.setText("0");
                    txaGhiChu.setText("");
                }
            }
    }//GEN-LAST:event_ThemAdd_Hall_List_DialogActionPerformed

    private void HuyEdit_Hall_List_DialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyEdit_Hall_List_DialogActionPerformed
        // TODO add your handling code here:
        Edit_Hall_List_Dialog.setVisible(false);
    }//GEN-LAST:event_HuyEdit_Hall_List_DialogActionPerformed

    private void ThemEdit_Edit_List_DialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemEdit_Edit_List_DialogActionPerformed
        // TODO add your handling code here:
        int row = Table_Hall.getSelectedRow();
        String maSanh = String.valueOf(Table_Hall.getValueAt(row, 1));
        int kq = 0;
        String tenSanh = txfTenSanhValue.getText();
        String tenLoaiSanh = cbxLoaiSanhValue.getSelectedItem().toString();
        String maLoaiSanh = mapMaLoaiSanh.get(tenLoaiSanh);
        int soLuongBanToiDa = Integer.parseInt(txfSoLuongBanToiDaValue.getText());
        int donGiaBanToiThieu = Integer.parseInt(txfDonGiaToiThieuValue.getText());
        String ghiChu = txaGhiChu.getText();
        if(Integer.parseInt(txfSoLuongBanToiDaValue.getText()) > 0){
            kq = SanhDAO.getInstance().Update(new Sanh(maSanh, maLoaiSanh, tenSanh, soLuongBanToiDa, tenLoaiSanh, donGiaBanToiThieu, ghiChu));
        }else{
            Message("Số lượng bàn tối đa phải lớn hơn 0", JOptionPane.WARNING_MESSAGE);
        }
        if (kq > 0) {
            Message("Cập nhật dữ liệu thành công", JOptionPane.WARNING_MESSAGE);
            Edit_Hall_List_Dialog.setVisible(false);
            ReloadDataTable();
        } else {
            Edit_Hall_List_Dialog.setVisible(true);
            Message("Chỉnh sửa dữ liệu thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ThemEdit_Edit_List_DialogActionPerformed

    private void cbxLoaiSanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiSanhActionPerformed
        // TODO add your handling code here:
        txfDonGiaToiThieu.setText(mapDonGiaBanToiThieu.get(cbxLoaiSanh.getSelectedItem()));
    }//GEN-LAST:event_cbxLoaiSanhActionPerformed

    private void cbxLoaiSanhValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiSanhValueActionPerformed
        // TODO add your handling code here:
        txfDonGiaToiThieuValue.setText(mapDonGiaBanToiThieu.get(cbxLoaiSanhValue.getSelectedItem()));
    }//GEN-LAST:event_cbxLoaiSanhValueActionPerformed

    private void txfSoLuongBanToiDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSoLuongBanToiDaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSoLuongBanToiDaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Add_Hall_List_Dialog;
    private javax.swing.JButton BackPage3;
    private javax.swing.JDialog Edit_Hall_List_Dialog;
    private javax.swing.JButton HuyAdd_Hall_List_Dialog;
    private javax.swing.JButton HuyEdit_Hall_List_Dialog;
    private javax.swing.JTable Table_Hall;
    private javax.swing.JButton ThemAdd_Hall_List_Dialog;
    private javax.swing.JButton ThemEdit_Edit_List_Dialog;
    private javax.swing.JButton btnAddHall;
    private javax.swing.JButton btnDeleteHall;
    private javax.swing.JButton btnEditHall;
    private javax.swing.JComboBox<String> cbxLoaiSanh;
    private javax.swing.JComboBox<String> cbxLoaiSanhValue;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txaGhiChu;
    private javax.swing.JTextField txaGhiChuValue;
    private javax.swing.JTextField txfDonGiaToiThieu;
    private javax.swing.JTextField txfDonGiaToiThieuValue;
    private javax.swing.JTextField txfSearchTable;
    private javax.swing.JTextField txfSoLuongBanToiDa;
    private javax.swing.JTextField txfSoLuongBanToiDaValue;
    private javax.swing.JTextField txfTenSanh;
    private javax.swing.JTextField txfTenSanhValue;
    // End of variables declaration//GEN-END:variables
}
